/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuccessRouteImport } from './routes/success'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClassesIndexRouteImport } from './routes/classes/index'
import { Route as ApiCanvasSettingsRouteImport } from './routes/api/canvas-settings'
import { Route as ClassesClassIdIndexRouteImport } from './routes/classes/$classId/index'
import { Route as ApiCanvasSyncActionRouteImport } from './routes/api/canvas-sync/$action'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ClassesClassIdModulesIndexRouteImport } from './routes/classes/$classId/modules/index'
import { Route as ClassesClassIdAssignmentsIndexRouteImport } from './routes/classes/$classId/assignments/index'
import { Route as ClassesClassIdAssignmentsAssignmentIdIndexRouteImport } from './routes/classes/$classId/assignments/$assignmentId/index'

const SuccessRoute = SuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassesIndexRoute = ClassesIndexRouteImport.update({
  id: '/classes/',
  path: '/classes/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCanvasSettingsRoute = ApiCanvasSettingsRouteImport.update({
  id: '/api/canvas-settings',
  path: '/api/canvas-settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassesClassIdIndexRoute = ClassesClassIdIndexRouteImport.update({
  id: '/classes/$classId/',
  path: '/classes/$classId/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCanvasSyncActionRoute = ApiCanvasSyncActionRouteImport.update({
  id: '/api/canvas-sync/$action',
  path: '/api/canvas-sync/$action',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassesClassIdModulesIndexRoute =
  ClassesClassIdModulesIndexRouteImport.update({
    id: '/classes/$classId/modules/',
    path: '/classes/$classId/modules/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ClassesClassIdAssignmentsIndexRoute =
  ClassesClassIdAssignmentsIndexRouteImport.update({
    id: '/classes/$classId/assignments/',
    path: '/classes/$classId/assignments/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ClassesClassIdAssignmentsAssignmentIdIndexRoute =
  ClassesClassIdAssignmentsAssignmentIdIndexRouteImport.update({
    id: '/classes/$classId/assignments/$assignmentId/',
    path: '/classes/$classId/assignments/$assignmentId/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/success': typeof SuccessRoute
  '/api/canvas-settings': typeof ApiCanvasSettingsRoute
  '/classes/': typeof ClassesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/canvas-sync/$action': typeof ApiCanvasSyncActionRoute
  '/classes/$classId/': typeof ClassesClassIdIndexRoute
  '/classes/$classId/assignments/': typeof ClassesClassIdAssignmentsIndexRoute
  '/classes/$classId/modules/': typeof ClassesClassIdModulesIndexRoute
  '/classes/$classId/assignments/$assignmentId/': typeof ClassesClassIdAssignmentsAssignmentIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/success': typeof SuccessRoute
  '/api/canvas-settings': typeof ApiCanvasSettingsRoute
  '/classes': typeof ClassesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/canvas-sync/$action': typeof ApiCanvasSyncActionRoute
  '/classes/$classId': typeof ClassesClassIdIndexRoute
  '/classes/$classId/assignments': typeof ClassesClassIdAssignmentsIndexRoute
  '/classes/$classId/modules': typeof ClassesClassIdModulesIndexRoute
  '/classes/$classId/assignments/$assignmentId': typeof ClassesClassIdAssignmentsAssignmentIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/success': typeof SuccessRoute
  '/api/canvas-settings': typeof ApiCanvasSettingsRoute
  '/classes/': typeof ClassesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/canvas-sync/$action': typeof ApiCanvasSyncActionRoute
  '/classes/$classId/': typeof ClassesClassIdIndexRoute
  '/classes/$classId/assignments/': typeof ClassesClassIdAssignmentsIndexRoute
  '/classes/$classId/modules/': typeof ClassesClassIdModulesIndexRoute
  '/classes/$classId/assignments/$assignmentId/': typeof ClassesClassIdAssignmentsAssignmentIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/success'
    | '/api/canvas-settings'
    | '/classes/'
    | '/api/auth/$'
    | '/api/canvas-sync/$action'
    | '/classes/$classId/'
    | '/classes/$classId/assignments/'
    | '/classes/$classId/modules/'
    | '/classes/$classId/assignments/$assignmentId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/success'
    | '/api/canvas-settings'
    | '/classes'
    | '/api/auth/$'
    | '/api/canvas-sync/$action'
    | '/classes/$classId'
    | '/classes/$classId/assignments'
    | '/classes/$classId/modules'
    | '/classes/$classId/assignments/$assignmentId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/success'
    | '/api/canvas-settings'
    | '/classes/'
    | '/api/auth/$'
    | '/api/canvas-sync/$action'
    | '/classes/$classId/'
    | '/classes/$classId/assignments/'
    | '/classes/$classId/modules/'
    | '/classes/$classId/assignments/$assignmentId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  SuccessRoute: typeof SuccessRoute
  ApiCanvasSettingsRoute: typeof ApiCanvasSettingsRoute
  ClassesIndexRoute: typeof ClassesIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiCanvasSyncActionRoute: typeof ApiCanvasSyncActionRoute
  ClassesClassIdIndexRoute: typeof ClassesClassIdIndexRoute
  ClassesClassIdAssignmentsIndexRoute: typeof ClassesClassIdAssignmentsIndexRoute
  ClassesClassIdModulesIndexRoute: typeof ClassesClassIdModulesIndexRoute
  ClassesClassIdAssignmentsAssignmentIdIndexRoute: typeof ClassesClassIdAssignmentsAssignmentIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/success': {
      id: '/success'
      path: '/success'
      fullPath: '/success'
      preLoaderRoute: typeof SuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classes/': {
      id: '/classes/'
      path: '/classes'
      fullPath: '/classes/'
      preLoaderRoute: typeof ClassesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/canvas-settings': {
      id: '/api/canvas-settings'
      path: '/api/canvas-settings'
      fullPath: '/api/canvas-settings'
      preLoaderRoute: typeof ApiCanvasSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classes/$classId/': {
      id: '/classes/$classId/'
      path: '/classes/$classId'
      fullPath: '/classes/$classId/'
      preLoaderRoute: typeof ClassesClassIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/canvas-sync/$action': {
      id: '/api/canvas-sync/$action'
      path: '/api/canvas-sync/$action'
      fullPath: '/api/canvas-sync/$action'
      preLoaderRoute: typeof ApiCanvasSyncActionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classes/$classId/modules/': {
      id: '/classes/$classId/modules/'
      path: '/classes/$classId/modules'
      fullPath: '/classes/$classId/modules/'
      preLoaderRoute: typeof ClassesClassIdModulesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classes/$classId/assignments/': {
      id: '/classes/$classId/assignments/'
      path: '/classes/$classId/assignments'
      fullPath: '/classes/$classId/assignments/'
      preLoaderRoute: typeof ClassesClassIdAssignmentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classes/$classId/assignments/$assignmentId/': {
      id: '/classes/$classId/assignments/$assignmentId/'
      path: '/classes/$classId/assignments/$assignmentId'
      fullPath: '/classes/$classId/assignments/$assignmentId/'
      preLoaderRoute: typeof ClassesClassIdAssignmentsAssignmentIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  SuccessRoute: SuccessRoute,
  ApiCanvasSettingsRoute: ApiCanvasSettingsRoute,
  ClassesIndexRoute: ClassesIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiCanvasSyncActionRoute: ApiCanvasSyncActionRoute,
  ClassesClassIdIndexRoute: ClassesClassIdIndexRoute,
  ClassesClassIdAssignmentsIndexRoute: ClassesClassIdAssignmentsIndexRoute,
  ClassesClassIdModulesIndexRoute: ClassesClassIdModulesIndexRoute,
  ClassesClassIdAssignmentsAssignmentIdIndexRoute:
    ClassesClassIdAssignmentsAssignmentIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
